// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type QuestionnaireIqiyi struct {
	ent.Schema
}

func (QuestionnaireIqiyi) Fields() []ent.Field {
	return []ent.Field{field.Int32("id"), field.String("wallet_address").Comment("wallet address"), field.String("twitter_url").Comment("twitter 主页"), field.String("invite_code").Comment("invite code"), field.String("q1").Comment("question 1"), field.String("q2").Comment("question 2"), field.String("q3").Comment("question 3"), field.String("q4").Comment("question 4"), field.String("q5").Comment("question 5"), field.String("q6").Comment("question 6"), field.String("q7").Comment("question 7"), field.String("balance").Optional().Comment("eth 余额"), field.Int32("amount").Optional().Comment("nft-数量"), field.Int32("transaction_count").Optional().Comment("交易总数"), field.Int8("answer").Optional().Comment("0 未反馈 1反馈通过 2未通过"), field.Time("updated_at").Comment("更新时间"), field.Time("deleted_at").Optional().Comment("删除时间"), field.Time("created_at").Comment("创建时间")}
}
func (QuestionnaireIqiyi) Edges() []ent.Edge {
	return nil
}
func (QuestionnaireIqiyi) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "questionnaire_iqiyi"}}
}
