// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ohdat/entmod/ent/predicate"
	"github.com/ohdat/entmod/ent/questionnaireiqiyi"
)

// QuestionnaireIqiyiDelete is the builder for deleting a QuestionnaireIqiyi entity.
type QuestionnaireIqiyiDelete struct {
	config
	hooks    []Hook
	mutation *QuestionnaireIqiyiMutation
}

// Where appends a list predicates to the QuestionnaireIqiyiDelete builder.
func (qid *QuestionnaireIqiyiDelete) Where(ps ...predicate.QuestionnaireIqiyi) *QuestionnaireIqiyiDelete {
	qid.mutation.Where(ps...)
	return qid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (qid *QuestionnaireIqiyiDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(qid.hooks) == 0 {
		affected, err = qid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*QuestionnaireIqiyiMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			qid.mutation = mutation
			affected, err = qid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(qid.hooks) - 1; i >= 0; i-- {
			if qid.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = qid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, qid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (qid *QuestionnaireIqiyiDelete) ExecX(ctx context.Context) int {
	n, err := qid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (qid *QuestionnaireIqiyiDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: questionnaireiqiyi.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: questionnaireiqiyi.FieldID,
			},
		},
	}
	if ps := qid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, qid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// QuestionnaireIqiyiDeleteOne is the builder for deleting a single QuestionnaireIqiyi entity.
type QuestionnaireIqiyiDeleteOne struct {
	qid *QuestionnaireIqiyiDelete
}

// Exec executes the deletion query.
func (qido *QuestionnaireIqiyiDeleteOne) Exec(ctx context.Context) error {
	n, err := qido.qid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{questionnaireiqiyi.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (qido *QuestionnaireIqiyiDeleteOne) ExecX(ctx context.Context) {
	qido.qid.ExecX(ctx)
}
