// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ohdat/entmod/ent/predicate"
	"github.com/ohdat/entmod/ent/questionnaireiqiyi"
)

// QuestionnaireIqiyiQuery is the builder for querying QuestionnaireIqiyi entities.
type QuestionnaireIqiyiQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.QuestionnaireIqiyi
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the QuestionnaireIqiyiQuery builder.
func (qiq *QuestionnaireIqiyiQuery) Where(ps ...predicate.QuestionnaireIqiyi) *QuestionnaireIqiyiQuery {
	qiq.predicates = append(qiq.predicates, ps...)
	return qiq
}

// Limit adds a limit step to the query.
func (qiq *QuestionnaireIqiyiQuery) Limit(limit int) *QuestionnaireIqiyiQuery {
	qiq.limit = &limit
	return qiq
}

// Offset adds an offset step to the query.
func (qiq *QuestionnaireIqiyiQuery) Offset(offset int) *QuestionnaireIqiyiQuery {
	qiq.offset = &offset
	return qiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (qiq *QuestionnaireIqiyiQuery) Unique(unique bool) *QuestionnaireIqiyiQuery {
	qiq.unique = &unique
	return qiq
}

// Order adds an order step to the query.
func (qiq *QuestionnaireIqiyiQuery) Order(o ...OrderFunc) *QuestionnaireIqiyiQuery {
	qiq.order = append(qiq.order, o...)
	return qiq
}

// First returns the first QuestionnaireIqiyi entity from the query.
// Returns a *NotFoundError when no QuestionnaireIqiyi was found.
func (qiq *QuestionnaireIqiyiQuery) First(ctx context.Context) (*QuestionnaireIqiyi, error) {
	nodes, err := qiq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{questionnaireiqiyi.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (qiq *QuestionnaireIqiyiQuery) FirstX(ctx context.Context) *QuestionnaireIqiyi {
	node, err := qiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first QuestionnaireIqiyi ID from the query.
// Returns a *NotFoundError when no QuestionnaireIqiyi ID was found.
func (qiq *QuestionnaireIqiyiQuery) FirstID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = qiq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{questionnaireiqiyi.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (qiq *QuestionnaireIqiyiQuery) FirstIDX(ctx context.Context) int32 {
	id, err := qiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single QuestionnaireIqiyi entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one QuestionnaireIqiyi entity is found.
// Returns a *NotFoundError when no QuestionnaireIqiyi entities are found.
func (qiq *QuestionnaireIqiyiQuery) Only(ctx context.Context) (*QuestionnaireIqiyi, error) {
	nodes, err := qiq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{questionnaireiqiyi.Label}
	default:
		return nil, &NotSingularError{questionnaireiqiyi.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (qiq *QuestionnaireIqiyiQuery) OnlyX(ctx context.Context) *QuestionnaireIqiyi {
	node, err := qiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only QuestionnaireIqiyi ID in the query.
// Returns a *NotSingularError when more than one QuestionnaireIqiyi ID is found.
// Returns a *NotFoundError when no entities are found.
func (qiq *QuestionnaireIqiyiQuery) OnlyID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = qiq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{questionnaireiqiyi.Label}
	default:
		err = &NotSingularError{questionnaireiqiyi.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (qiq *QuestionnaireIqiyiQuery) OnlyIDX(ctx context.Context) int32 {
	id, err := qiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of QuestionnaireIqiyis.
func (qiq *QuestionnaireIqiyiQuery) All(ctx context.Context) ([]*QuestionnaireIqiyi, error) {
	if err := qiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return qiq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (qiq *QuestionnaireIqiyiQuery) AllX(ctx context.Context) []*QuestionnaireIqiyi {
	nodes, err := qiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of QuestionnaireIqiyi IDs.
func (qiq *QuestionnaireIqiyiQuery) IDs(ctx context.Context) ([]int32, error) {
	var ids []int32
	if err := qiq.Select(questionnaireiqiyi.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (qiq *QuestionnaireIqiyiQuery) IDsX(ctx context.Context) []int32 {
	ids, err := qiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (qiq *QuestionnaireIqiyiQuery) Count(ctx context.Context) (int, error) {
	if err := qiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return qiq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (qiq *QuestionnaireIqiyiQuery) CountX(ctx context.Context) int {
	count, err := qiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (qiq *QuestionnaireIqiyiQuery) Exist(ctx context.Context) (bool, error) {
	if err := qiq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return qiq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (qiq *QuestionnaireIqiyiQuery) ExistX(ctx context.Context) bool {
	exist, err := qiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the QuestionnaireIqiyiQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (qiq *QuestionnaireIqiyiQuery) Clone() *QuestionnaireIqiyiQuery {
	if qiq == nil {
		return nil
	}
	return &QuestionnaireIqiyiQuery{
		config:     qiq.config,
		limit:      qiq.limit,
		offset:     qiq.offset,
		order:      append([]OrderFunc{}, qiq.order...),
		predicates: append([]predicate.QuestionnaireIqiyi{}, qiq.predicates...),
		// clone intermediate query.
		sql:    qiq.sql.Clone(),
		path:   qiq.path,
		unique: qiq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		WalletAddress string `json:"wallet_address,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.QuestionnaireIqiyi.Query().
//		GroupBy(questionnaireiqiyi.FieldWalletAddress).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (qiq *QuestionnaireIqiyiQuery) GroupBy(field string, fields ...string) *QuestionnaireIqiyiGroupBy {
	grbuild := &QuestionnaireIqiyiGroupBy{config: qiq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := qiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return qiq.sqlQuery(ctx), nil
	}
	grbuild.label = questionnaireiqiyi.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		WalletAddress string `json:"wallet_address,omitempty"`
//	}
//
//	client.QuestionnaireIqiyi.Query().
//		Select(questionnaireiqiyi.FieldWalletAddress).
//		Scan(ctx, &v)
func (qiq *QuestionnaireIqiyiQuery) Select(fields ...string) *QuestionnaireIqiyiSelect {
	qiq.fields = append(qiq.fields, fields...)
	selbuild := &QuestionnaireIqiyiSelect{QuestionnaireIqiyiQuery: qiq}
	selbuild.label = questionnaireiqiyi.Label
	selbuild.flds, selbuild.scan = &qiq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a QuestionnaireIqiyiSelect configured with the given aggregations.
func (qiq *QuestionnaireIqiyiQuery) Aggregate(fns ...AggregateFunc) *QuestionnaireIqiyiSelect {
	return qiq.Select().Aggregate(fns...)
}

func (qiq *QuestionnaireIqiyiQuery) prepareQuery(ctx context.Context) error {
	for _, f := range qiq.fields {
		if !questionnaireiqiyi.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if qiq.path != nil {
		prev, err := qiq.path(ctx)
		if err != nil {
			return err
		}
		qiq.sql = prev
	}
	return nil
}

func (qiq *QuestionnaireIqiyiQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*QuestionnaireIqiyi, error) {
	var (
		nodes = []*QuestionnaireIqiyi{}
		_spec = qiq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*QuestionnaireIqiyi).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &QuestionnaireIqiyi{config: qiq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, qiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (qiq *QuestionnaireIqiyiQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := qiq.querySpec()
	_spec.Node.Columns = qiq.fields
	if len(qiq.fields) > 0 {
		_spec.Unique = qiq.unique != nil && *qiq.unique
	}
	return sqlgraph.CountNodes(ctx, qiq.driver, _spec)
}

func (qiq *QuestionnaireIqiyiQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := qiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (qiq *QuestionnaireIqiyiQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   questionnaireiqiyi.Table,
			Columns: questionnaireiqiyi.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: questionnaireiqiyi.FieldID,
			},
		},
		From:   qiq.sql,
		Unique: true,
	}
	if unique := qiq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := qiq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, questionnaireiqiyi.FieldID)
		for i := range fields {
			if fields[i] != questionnaireiqiyi.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := qiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := qiq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := qiq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := qiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (qiq *QuestionnaireIqiyiQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(qiq.driver.Dialect())
	t1 := builder.Table(questionnaireiqiyi.Table)
	columns := qiq.fields
	if len(columns) == 0 {
		columns = questionnaireiqiyi.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if qiq.sql != nil {
		selector = qiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if qiq.unique != nil && *qiq.unique {
		selector.Distinct()
	}
	for _, p := range qiq.predicates {
		p(selector)
	}
	for _, p := range qiq.order {
		p(selector)
	}
	if offset := qiq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := qiq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// QuestionnaireIqiyiGroupBy is the group-by builder for QuestionnaireIqiyi entities.
type QuestionnaireIqiyiGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (qigb *QuestionnaireIqiyiGroupBy) Aggregate(fns ...AggregateFunc) *QuestionnaireIqiyiGroupBy {
	qigb.fns = append(qigb.fns, fns...)
	return qigb
}

// Scan applies the group-by query and scans the result into the given value.
func (qigb *QuestionnaireIqiyiGroupBy) Scan(ctx context.Context, v any) error {
	query, err := qigb.path(ctx)
	if err != nil {
		return err
	}
	qigb.sql = query
	return qigb.sqlScan(ctx, v)
}

func (qigb *QuestionnaireIqiyiGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range qigb.fields {
		if !questionnaireiqiyi.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := qigb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qigb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (qigb *QuestionnaireIqiyiGroupBy) sqlQuery() *sql.Selector {
	selector := qigb.sql.Select()
	aggregation := make([]string, 0, len(qigb.fns))
	for _, fn := range qigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(qigb.fields)+len(qigb.fns))
		for _, f := range qigb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(qigb.fields...)...)
}

// QuestionnaireIqiyiSelect is the builder for selecting fields of QuestionnaireIqiyi entities.
type QuestionnaireIqiyiSelect struct {
	*QuestionnaireIqiyiQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (qis *QuestionnaireIqiyiSelect) Aggregate(fns ...AggregateFunc) *QuestionnaireIqiyiSelect {
	qis.fns = append(qis.fns, fns...)
	return qis
}

// Scan applies the selector query and scans the result into the given value.
func (qis *QuestionnaireIqiyiSelect) Scan(ctx context.Context, v any) error {
	if err := qis.prepareQuery(ctx); err != nil {
		return err
	}
	qis.sql = qis.QuestionnaireIqiyiQuery.sqlQuery(ctx)
	return qis.sqlScan(ctx, v)
}

func (qis *QuestionnaireIqiyiSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(qis.fns))
	for _, fn := range qis.fns {
		aggregation = append(aggregation, fn(qis.sql))
	}
	switch n := len(*qis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		qis.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		qis.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := qis.sql.Query()
	if err := qis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
