// Code generated by ent, DO NOT EDIT.

package questionnaireiqiyi

const (
	// Label holds the string label denoting the questionnaireiqiyi type in the database.
	Label = "questionnaire_iqiyi"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldWalletAddress holds the string denoting the wallet_address field in the database.
	FieldWalletAddress = "wallet_address"
	// FieldTwitterURL holds the string denoting the twitter_url field in the database.
	FieldTwitterURL = "twitter_url"
	// FieldInviteCode holds the string denoting the invite_code field in the database.
	FieldInviteCode = "invite_code"
	// FieldQ1 holds the string denoting the q1 field in the database.
	FieldQ1 = "q1"
	// FieldQ2 holds the string denoting the q2 field in the database.
	FieldQ2 = "q2"
	// FieldQ3 holds the string denoting the q3 field in the database.
	FieldQ3 = "q3"
	// FieldQ4 holds the string denoting the q4 field in the database.
	FieldQ4 = "q4"
	// FieldQ5 holds the string denoting the q5 field in the database.
	FieldQ5 = "q5"
	// FieldQ6 holds the string denoting the q6 field in the database.
	FieldQ6 = "q6"
	// FieldQ7 holds the string denoting the q7 field in the database.
	FieldQ7 = "q7"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldTransactionCount holds the string denoting the transaction_count field in the database.
	FieldTransactionCount = "transaction_count"
	// FieldAnswer holds the string denoting the answer field in the database.
	FieldAnswer = "answer"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the questionnaireiqiyi in the database.
	Table = "questionnaire_iqiyi"
)

// Columns holds all SQL columns for questionnaireiqiyi fields.
var Columns = []string{
	FieldID,
	FieldWalletAddress,
	FieldTwitterURL,
	FieldInviteCode,
	FieldQ1,
	FieldQ2,
	FieldQ3,
	FieldQ4,
	FieldQ5,
	FieldQ6,
	FieldQ7,
	FieldBalance,
	FieldAmount,
	FieldTransactionCount,
	FieldAnswer,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
