// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// QuestionnaireIqiyi is the predicate function for questionnaireiqiyi builders.
type QuestionnaireIqiyi func(*sql.Selector)
